-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 22:29:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `Country` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Unique id` VARCHAR(45) NOT NULL,
  `International id airport` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Unique id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `ConstructorsName` VARCHAR(45) NOT NULL,
  `Weight` INT NOT NULL,
  `Numberofseats` INT NOT NULL,
  `Model id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Model id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplanes` (
  `I.D.` INT NOT NULL,
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  `Model_Model id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`I.D.`),
  INDEX `fk_Airplanes_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  INDEX `fk_Airplanes_Model1_idx` (`Model_Model id` ASC) VISIBLE,
  CONSTRAINT `fk_Airplanes_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airplanes_Model1`
    FOREIGN KEY (`Model_Model id`)
    REFERENCES `mydb`.`Model` (`Model id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `Name` VARCHAR(45) NOT NULL,
  `Origin Country of Airline` VARCHAR(45) NOT NULL,
  `International id of company` VARCHAR(45) NOT NULL,
  `Function indication` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`International id of company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `Time and day of arrival` DATETIME NOT NULL,
  `Time and day of departure` DATETIME NOT NULL,
  `Airport_Unique id arrival` VARCHAR(45) NOT NULL,
  `Airport_Unique id1 departure` VARCHAR(45) NOT NULL,
  `Airplanes_I.D.` INT NOT NULL,
  `Airline_International id of company` VARCHAR(45) NOT NULL,
  `Flight code` VARCHAR(45) NOT NULL,
  INDEX `fk_Flight_Airport1_idx` (`Airport_Unique id arrival` ASC) VISIBLE,
  INDEX `fk_Flight_Airport2_idx` (`Airport_Unique id1 departure` ASC) VISIBLE,
  INDEX `fk_Flight_Airplanes1_idx` (`Airplanes_I.D.` ASC) VISIBLE,
  INDEX `fk_Flight_Airline1_idx` (`Airline_International id of company` ASC) VISIBLE,
  PRIMARY KEY (`Flight code`),
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`Airport_Unique id arrival`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport2`
    FOREIGN KEY (`Airport_Unique id1 departure`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airplanes1`
    FOREIGN KEY (`Airplanes_I.D.`)
    REFERENCES `mydb`.`Airplanes` (`I.D.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_International id of company`)
    REFERENCES `mydb`.`Airline` (`International id of company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `Type` ENUM('First Class ', 'Business Class', ' Premium Economy', 'Economy Class') NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Name` VARCHAR(45) NOT NULL,
  `Seat_Type1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`),
  INDEX `fk_Menu_Seat1_idx` (`Seat_Type1` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Seat1`
    FOREIGN KEY (`Seat_Type1`)
    REFERENCES `mydb`.`Seat` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination Certificate` (
  `Date of Last Vaccination` DATE NOT NULL,
  `Number of doses` INT NOT NULL,
  `Vaccination code` INT NOT NULL,
  PRIMARY KEY (`Vaccination code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `Email` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Phone number` INT NOT NULL,
  `Id code` VARCHAR(45) NOT NULL,
  `Vaccination Certificate_Vaccination code` INT NULL,
  PRIMARY KEY (`Id code`),
  INDEX `fk_Person_Vaccination Certificate1_idx` (`Vaccination Certificate_Vaccination code` ASC) VISIBLE,
  CONSTRAINT `fk_Person_Vaccination Certificate1`
    FOREIGN KEY (`Vaccination Certificate_Vaccination code`)
    REFERENCES `mydb`.`Vaccination Certificate` (`Vaccination code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manifest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manifest` (
  `Manifest Code` INT NOT NULL,
  `Flight_Flight code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Manifest Code`),
  INDEX `fk_Manifest_Flight1_idx` (`Flight_Flight code` ASC) VISIBLE,
  CONSTRAINT `fk_Manifest_Flight1`
    FOREIGN KEY (`Flight_Flight code`)
    REFERENCES `mydb`.`Flight` (`Flight code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`System of reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`System of reservations` (
  `Seat_Type` VARCHAR(45) NOT NULL,
  `Reservation code` VARCHAR(45) NOT NULL,
  `Date of reservation` DATE NOT NULL,
  `Comments` MEDIUMTEXT NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  `Manifest_Manifest Code` INT NOT NULL,
  PRIMARY KEY (`Reservation code`),
  INDEX `fk_System of reservations_has_Ticket_Seat1_idx` (`Seat_Type` ASC) VISIBLE,
  INDEX `fk_System of reservations_has_Ticket_Person1_idx` (`Person_Id code` ASC) VISIBLE,
  INDEX `fk_System of reservations_has_Ticket_Manifest1_idx` (`Manifest_Manifest Code` ASC) VISIBLE,
  CONSTRAINT `fk_System of reservations_has_Ticket_Seat1`
    FOREIGN KEY (`Seat_Type`)
    REFERENCES `mydb`.`Seat` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_System of reservations_has_Ticket_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_System of reservations_has_Ticket_Manifest1`
    FOREIGN KEY (`Manifest_Manifest Code`)
    REFERENCES `mydb`.`Manifest` (`Manifest Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `QR-code` VARCHAR(45) NOT NULL,
  `Publication date` DATE NOT NULL,
  `System of reservations_has_Ticket_Reservation code` VARCHAR(45) NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`QR-code`),
  INDEX `fk_Ticket_System of reservations_has_Ticket1_idx` (`System of reservations_has_Ticket_Reservation code` ASC) VISIBLE,
  INDEX `fk_Ticket_Person1_idx` (`Person_Id code` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_System of reservations_has_Ticket1`
    FOREIGN KEY (`System of reservations_has_Ticket_Reservation code`)
    REFERENCES `mydb`.`System of reservations` (`Reservation code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Models` (
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  `Model_Model id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airport_Unique id`, `Model_Model id`),
  INDEX `fk_Airport_has_Model_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  INDEX `fk_Airport_has_Models_Model1_idx` (`Model_Model id` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Model_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Models_Model1`
    FOREIGN KEY (`Model_Model id`)
    REFERENCES `mydb`.`Model` (`Model id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Airlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Airlines` (
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  `Airline_International id of company` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airport_Unique id`, `Airline_International id of company`),
  INDEX `fk_Airport_has_AviationCompanies_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  INDEX `fk_Airport_has_Airlines_Airline1_idx` (`Airline_International id of company` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_AviationCompanies_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Airlines_Airline1`
    FOREIGN KEY (`Airline_International id of company`)
    REFERENCES `mydb`.`Airline` (`International id of company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `Passenger Passport` INT NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  `Ticket_QR-code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Person_Id code`, `Ticket_QR-code`),
  INDEX `fk_Passenger_Person1_idx` (`Person_Id code` ASC) VISIBLE,
  INDEX `fk_Passenger_Ticket1_idx` (`Ticket_QR-code` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passenger_Ticket1`
    FOREIGN KEY (`Ticket_QR-code`)
    REFERENCES `mydb`.`Ticket` (`QR-code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Research` (
  `Title` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Description with general information` MEDIUMTEXT NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  `Flight_Flight code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`, `Type`, `Flight_Flight code`),
  INDEX `fk_Research_Person1_idx` (`Person_Id code` ASC) VISIBLE,
  INDEX `fk_Research_Flight1_idx` (`Flight_Flight code` ASC) VISIBLE,
  CONSTRAINT `fk_Research_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Research_Flight1`
    FOREIGN KEY (`Flight_Flight code`)
    REFERENCES `mydb`.`Flight` (`Flight code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `Name` VARCHAR(45) NOT NULL,
  `Foundation date` DATE NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `Salary` INT NOT NULL,
  `Union_Name` VARCHAR(45) NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  INDEX `fk_Technician_Union1_idx` (`Union_Name` ASC) VISIBLE,
  PRIMARY KEY (`Person_Id code`, `Airport_Unique id`),
  INDEX `fk_Technician_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_Union1`
    FOREIGN KEY (`Union_Name`)
    REFERENCES `mydb`.`Union` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inspector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inspector` (
  `Date of recent checkup` DATE NOT NULL,
  `Union_Name` VARCHAR(45) NOT NULL,
  `Person_Id code` VARCHAR(45) NOT NULL,
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Person_Id code`, `Airport_Unique id`),
  INDEX `fk_Inspector_Union1_idx` (`Union_Name` ASC) VISIBLE,
  INDEX `fk_Inspector_Person1_idx` (`Person_Id code` ASC) VISIBLE,
  INDEX `fk_Inspector_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  CONSTRAINT `fk_Inspector_Union1`
    FOREIGN KEY (`Union_Name`)
    REFERENCES `mydb`.`Union` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inspector_Person1`
    FOREIGN KEY (`Person_Id code`)
    REFERENCES `mydb`.`Person` (`Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inspector_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Check` (
  `Name` VARCHAR(45) NOT NULL,
  `Max score` INT NOT NULL,
  `Check code` VARCHAR(45) NOT NULL,
  `Airplanes_I.D.` INT NOT NULL,
  PRIMARY KEY (`Check code`),
  INDEX `fk_Check_Airplanes1_idx` (`Airplanes_I.D.` ASC) VISIBLE,
  CONSTRAINT `fk_Check_Airplanes1`
    FOREIGN KEY (`Airplanes_I.D.`)
    REFERENCES `mydb`.`Airplanes` (`I.D.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Checks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Checks` (
  `Airport_Unique id` VARCHAR(45) NOT NULL,
  `Check_Check code` VARCHAR(45) NOT NULL,
  `Score` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Hours of check` INT NOT NULL,
  PRIMARY KEY (`Check_Check code`),
  INDEX `fk_Airport_has_Check_Check1_idx` (`Check_Check code` ASC) VISIBLE,
  INDEX `fk_Airport_has_Check_Airport1_idx` (`Airport_Unique id` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Check_Airport1`
    FOREIGN KEY (`Airport_Unique id`)
    REFERENCES `mydb`.`Airport` (`Unique id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Check_Check1`
    FOREIGN KEY (`Check_Check code`)
    REFERENCES `mydb`.`Check` (`Check code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician_has_Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician_has_Models` (
  `Technician_Person_Id code` VARCHAR(45) NOT NULL,
  `Model_Model id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Technician_Person_Id code`, `Model_Model id`),
  INDEX `fk_Technician_has_Model_Technician1_idx` (`Technician_Person_Id code` ASC) VISIBLE,
  INDEX `fk_Technician_has_Models_Model1_idx` (`Model_Model id` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_has_Model_Technician1`
    FOREIGN KEY (`Technician_Person_Id code`)
    REFERENCES `mydb`.`Technician` (`Person_Id code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_has_Models_Model1`
    FOREIGN KEY (`Model_Model id`)
    REFERENCES `mydb`.`Model` (`Model id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight_has_Menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight_has_Menus` (
  `Flight_Flight code` VARCHAR(45) NOT NULL,
  `Menu_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Flight_Flight code`, `Menu_Name`),
  INDEX `fk_Flight_has_Menu_Menu1_idx` (`Menu_Name` ASC) VISIBLE,
  INDEX `fk_Flight_has_Menu_Flight1_idx` (`Flight_Flight code` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_has_Menu_Flight1`
    FOREIGN KEY (`Flight_Flight code`)
    REFERENCES `mydb`.`Flight` (`Flight code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Menu_Menu1`
    FOREIGN KEY (`Menu_Name`)
    REFERENCES `mydb`.`Menu` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
